name = "whiteboard"
type = "javascript"
workers_dev = true
compatibility_date = "2021-11-08"
account_id = "7e155f728b0311833218e72046aaa90a"

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.mjs"
rules = [{type = "Text", globs = ["**/*.json"]}]

[site]
bucket = "./assets"
entry-point = "./dist"

[triggers]
crons = ["*/10 * * * *"]

[durable_objects]
bindings = [
  { name = "manager", class_name = "RoomManager" },
  { name = "rooms", class_name = "Room" },
  { name = "limiters", class_name = "RateLimiter" }
]

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom", "RateLimiter"]

[[migrations]]
tag = "v2"
new_classes = ["RoomManager"]

[[migrations]]
tag = "v3"
renamed_classes = [{from = "ChatRoom", to = "Room" }]