name = "edge-chat-demo"
type = "javascript"
workers_dev = true
compatibility_date = "2021-11-08"
account_id = "7e155f728b0311833218e72046aaa90a"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.mjs"
rules = [{type = "Data", globs = ["**/*.html", "**/*.json"]}]

[site]
bucket = "./assets"
entry-point = "./dist"

[triggers]
crons = ["* * * * *"]

[durable_objects]
bindings = [
  { name = "manager", class_name = "RoomManager" },
  { name = "rooms", class_name = "ChatRoom" },
  { name = "limiters", class_name = "RateLimiter" }
]

# Indicate that you want the ChatRoom and RateLimiter classes to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom", "RateLimiter"]

[[migrations]]
tag = "v2" # Should be unique for each entry
new_classes = ["RoomManager"]